services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    volumes:
      - ./backend:/app
      - model-cache:/root/.cache
      - chroma-data:/app/chroma_store
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always

volumes:
  model-cache:  # Persistent volume for all ML models
  chroma-data:  # Persistent volume for ChromaDB storage
